### ISSUE TITLE
[0731] D2_1984. 중간 평균값 구하기

### ISSUE THREAD

**Issue by kyungwonS928** [ALgorithmStudy1217/ALSS_SWEA#2]
https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AV5Pw_-KAdcDFAUq&categoryId=AV5Pw_-KAdcDFAUq&categoryType=CODE&problemTitle=1984&orderBy=FIRST_REG_DATETIME&selectCodeLang=ALL&select-1=&pageSize=10&pageIndex=1

**Comment by cheongmok** [comment]
https://github.com/ALgorithmStudy1217/ALSS_SWEA/commit/08376617d94f2c449a127ea4a8e4b5c56c24cd6b
